# Generated by Django 4.1.3 on 2022-11-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
